Ejemplo del libro de Ciaburro: https://github.com/PacktPublishing/Hands-On-Simulation-Modeling-with-Python-Second-Edition

In [1]:
import numpy as np

In [2]:
var_values = [1,-3,4.5,2]
num_coeff = 4
pop_chrom = 10 
sel_rate = 5

pop_size = (pop_chrom,num_coeff) 
pop_new = np.random.uniform(low=-10.0, high=10.0, size=pop_size)
print(pop_new)

[[ 1.26713439  8.36711277  3.17002586  7.89568735]
 [-4.61925737 -7.07782573  1.87942385  6.52620268]
 [ 4.63770283  7.43863722  7.1053577   3.83291799]
 [-1.72884071  4.72361439 -6.70723216 -7.24834753]
 [-0.28746463 -2.64086959  6.20521148 -1.02569629]
 [ 7.83415085 -2.85796613 -7.78725575  3.78721145]
 [ 7.50178243 -1.37297815 -8.95026437 -0.63519445]
 [-2.15364223 -9.56200488  3.44920517 -8.91439619]
 [ 0.08824716  7.05184597 -1.91751036  2.04807437]
 [-7.52080973  0.0655907   1.44843478 -2.74611741]]


In [3]:
num_gen = 100
for k in range(num_gen):
    fitness = np.sum(pop_new *var_values, axis=1)
    par_sel = np.empty((sel_rate, pop_new.shape[1]))
    print("Current generation = ", k)
    print("Best fitness value : ", np.max(fitness))
    
    for i in range(sel_rate):
        sel_id = np.where(fitness == np.max(fitness))
        sel_id = sel_id[0][0]
        par_sel[i, :] = pop_new[sel_id, :]
        fitness[sel_id]=np.min(fitness)

    offspring_size=(pop_chrom-sel_rate, num_coeff)
    offspring = np.empty(offspring_size)
    crossover_lenght = int(offspring_size[1]/2)
    
    for j in range(offspring_size[0]):
        par1_id = np.random.randint(0,par_sel.shape[0])
        par2_id = np.random.randint(0,par_sel.shape[0])
        offspring[j, 0:crossover_lenght] = par_sel[par1_id, 0:crossover_lenght]
        offspring[j, crossover_lenght:] = par_sel[par2_id, crossover_lenght:]
    

    for m in range(offspring.shape[0]):
        mut_val = np.random.uniform(-1.0, 1.0)
        mut_id = np.random.randint(0,par_sel.shape[1])
        offspring[m, mut_id] = offspring[m, mut_id] + mut_val 

    pop_new[0:par_sel.shape[0], :] = par_sel
    pop_new[par_sel.shape[0]:, :] = offspring


fitness = np.sum(pop_new *var_values, axis=1)
best_id = np.where(fitness == np.max(fitness))
print("Optimized coefficient values = ", pop_new[best_id, :])
print("Maximum value of y = ", fitness[best_id])


Current generation =  0
Best fitness value :  38.12403252329326
Current generation =  1
Best fitness value :  55.0279756534466
Current generation =  2
Best fitness value :  55.0279756534466
Current generation =  3
Best fitness value :  55.0279756534466
Current generation =  4
Best fitness value :  55.0279756534466
Current generation =  5
Best fitness value :  57.100625961104285
Current generation =  6
Best fitness value :  57.100625961104285
Current generation =  7
Best fitness value :  57.100625961104285
Current generation =  8
Best fitness value :  59.13849649815927
Current generation =  9
Best fitness value :  59.13849649815927
Current generation =  10
Best fitness value :  62.58073698635221
Current generation =  11
Best fitness value :  63.555764468574495
Current generation =  12
Best fitness value :  63.79868992784346
Current generation =  13
Best fitness value :  67.44410101288304
Current generation =  14
Best fitness value :  67.44410101288304
Current generation =  15
Best fitne